nguage: generic

env:
          global:
                      - APM_TEST_PACKAGES=""
                            - ATOM_LINT_WITH_BUNDLED_NODE="true"

                                matrix:
                                            - ATOM_CHANNEL=stable
                                                  - ATOM_CHANNEL=beta

                                                    ### Generic setup follows ###
                                                    script:
                                                    - yarn install 
                                                    - yarn run build

                                                    install: 
                                                    - yarn install

                                                    notifications:
                                                    email:
                                                    on_success: never
                                                    on_failure: change
                                                    
                                                    branches:
                                                    only:
                                                    - master
                                                    
                                                    git:
                                                    depth: 10
                                                    
                                                    sudo: false
                                                    
                                                    dist: trusty
                                                    
                                                    addons:
                                                    apt:
                                                    packages:
                                                    - build-essential
                                                    - fakeroot
                                                    - git
                                                    - libsecret-1-dev


                                                    deploy: 
                                                    provide: pages
                                                    skip-cleanup: true
                                                    github-token: $GITHUB_TOKEN
                                                    on: 
                                                    branch: master
